In [ ]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = '/content/drive/MyDrive/auto judge/problems_data.jsonl'
df = pd.read_json(file_path, lines=True)
df.head()

,title,description,input_description,output_description,sample_io,problem_class,problem_score,url
0,Uuu,Unununium (Uuu) was the name of the chemical\n...,The input consists of one line with two intege...,The output consists of $M$ lines where the $i$...,"[{'input': '7 10', 'output': '1 2 2 3 1 3 3 4 ...",hard,9.7,https://open.kattis.com/problems/uuu
1,House Building,A number of eccentrics from central New York h...,"The input consists of $10$ test cases, which a...",Print $K$ lines with\n the positions of the...,"[{'input': '0 2 3 2 50 60 50 30 50 40', 'outpu...",hard,9.7,https://open.kattis.com/problems/husbygge
2,Mario or Luigi,Mario and Luigi are playing a game where they ...,,,"[{'input': '', 'output': ''}]",hard,9.6,https://open.kattis.com/problems/marioorluigi
3,The Wire Ghost,Žofka is bending a copper wire. She starts wit...,The first line contains two integers $L$ and $...,The output consists of a single line consistin...,"[{'input': '4 3 3 C 2 C 1 C', 'output': 'GHOST...",hard,9.6,https://open.kattis.com/problems/thewireghost
4,Barking Up The Wrong Tree,"Your dog Spot is let loose in the park. Well, ...",The first line of input consists of two intege...,Write a single line containing the length need...,"[{'input': '2 0 10 0 10 10', 'output': '14.14'...",hard,9.6,https://open.kattis.com/problems/barktree

In [ ]:
df.shape

(4112, 8)

In [ ]:
df.columns

Index(['title', 'description', 'input_description', 'output_description',
       'sample_io', 'problem_class', 'problem_score', 'url'],
      dtype='object')

In [ ]:
df = df.drop(['sample_io','url'], axis=1)

In [ ]:
df.columns

Index(['title', 'description', 'input_description', 'output_description',
       'problem_class', 'problem_score'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4112 entries, 0 to 4111
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               4112 non-null   object
 1   description         4112 non-null   object
 2   input_description   4112 non-null   object
 3   output_description  4112 non-null   object
 4   problem_class       4112 non-null   object
 5   problem_score       4112 non-null   float64
dtypes: float64(1), object(5)
memory usage: 192.9+ KB

In [ ]:
df.isnull().sum()

title                 0
description           0
input_description     0
output_description    0
problem_class         0
problem_score         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(1)

### Data cleaning

In [ ]:
# the given dataset has no missing values so data is partially cleaned

In [ ]:
df['problem_class'].value_counts(normalize=True) * 100

problem_class
hard      47.203307
medium    34.168288
easy      18.628405
Name: proportion, dtype: float64

In [ ]:
# comnining text
df['combined_text'] = (
    df['title'] + " " +
    df['description'] + " " +
    df['input_description'] + " " +
    df['output_description']
)

### Text cleaning

In [ ]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df['clean_text'] = df['combined_text'].apply(clean_text)

In [ ]:
df[['clean_text', 'problem_class', 'problem_score']].head()

,clean_text,problem_class,problem_score
0,uuu unununium uuu was the name of the chemical...,hard,9.7
1,house building a number of eccentrics from cen...,hard,9.7
2,mario or luigi mario and luigi are playing a g...,hard,9.6
3,the wire ghost ofka is bending a copper wire s...,hard,9.6
4,barking up the wrong tree your dog spot is let...,hard,9.6

In [ ]:
clean_df = df[
    [
        'title',
        'description',
        'input_description',
        'output_description',
        'clean_text',
        'problem_class',
        'problem_score'
    ]
]

In [ ]:
file_path = "//content/drive/MyDrive/auto judge/AutoJudge_cleaned_dataset.csv"
clean_df.to_csv(file_path, index=False)

In [ ]:
clean_df.to_pickle("/content/AutoJudge_cleaned_dataset.pkl")